import Header from "@/components/layout/Header";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });
  const {
    data: { user },
  } = await supabase.auth.getUser();
  let cartItems: {
    id: number;
    product_id: number;
    quantity: number;
  }[] = [];

  if (user) {
    const { data, error } = await supabase
      .from("carts")
      .select("id, product_id, quantity")
      .eq("user_id", user.id);
    if (!error) {
      cartItems = data;
    }
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen">
          <Header user={user} cartItems={cartItems} />
          {children}
        </main>
      </body>
    </html>
  );
}
